### ISSUE TITLE
Demo site?

### ISSUE THREAD

**Issue by dlewand691** [simple-integrated-marketing/harmony#12]
Any chance you could put together a demo site? Would love to see all the features, I've been looking for something comprehensive like this. Thanks so much!

**Comment by ben-rogerson** [comment]
Hey Daniel, thanks for stumbling across our harmony repo. We're looking into a demo site with proper documentation and hopefully we'll have something ready for you soon.
We'll let you know when it's ready to take a look.

**Comment by ben-rogerson** [comment]
Hey Daniel - you can view the demo site @ https://harmony-demo.netlify.com
